/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AronGame {
    }
}
declare global {
    interface HTMLAronGameElement extends Components.AronGame, HTMLStencilElement {
    }
    var HTMLAronGameElement: {
        prototype: HTMLAronGameElement;
        new (): HTMLAronGameElement;
    };
    interface HTMLElementTagNameMap {
        "aron-game": HTMLAronGameElement;
    }
}
declare namespace LocalJSX {
    interface AronGame {
    }
    interface IntrinsicElements {
        "aron-game": AronGame;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aron-game": LocalJSX.AronGame & JSXBase.HTMLAttributes<HTMLAronGameElement>;
        }
    }
}
